name: gbnenvdev
channels:
  - conda-forge
dependencies:
  - python>=3.10
  - matplotlib
  - osmnx>=2
  - tqdm
  - geojson

  # extra to non-dev env
  - ipykernel
  - pytest
  - sphinx
  - numpydoc
  - myst-nb
  - nbsphinx
  - jupyter_sphinx
  - myst-parser
  - pre-commit
  - pip:
      # not available via conda-forge:
      - sphinxcontrib-bibtex
      - sphinx-copybutton
      - growbikenet>=0.10.1
      - furo