name: gbnenvdev
channels:
  - conda-forge
dependencies:
  - python>=3.12
  - matplotlib
  - osmnx>=2
  - tqdm
  - geojson

  # additional to the non-dev env
  - ipykernel
  - pytest
  - sphinx
  - numpydoc
  - myst-nb
  - nbsphinx
  - jupyter_sphinx
  - myst-parser
  - pre-commit
  - jupyterlab
  - pixi-kernel
  - growbikenet
  - pip:
      # not available via conda-forge:
      - sphinxcontrib-bibtex
      - sphinx-copybutton
      - furo